### PR TITLE
output paid amount in FIL not attoFIL

### LINKED ISSUE #33: glif agent pay to-current
I only borrowed 1 FIL... so the panic is one issue but the payment of 2302130898021 FIL is another.
```
❯ glif agent pay to-current
2023/05/16 12:11:48 Paying 2302130898021 FIL to the infinity-pool
-Transaction: 0x4d85ec0cc11d60e24c7ff95571a1493959df5ae42541069679dbccd7c65867fd
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/glif-confidential/cli/cmd.glob..func14(0x101599fe0, {0x1015db3e0, 0x0, 0x0?})
	/Users/lanzafame/src/github.com/glif-confidential/cli/cmd/agent_pay_current.go:56 +0x49f
github.com/spf13/cobra.(*Command).execute(0x101599fe0, {0x1015db3e0, 0x0, 0x0})
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x101599740)
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/glif-confidential/cli/cmd.Execute()
	/Users/lanzafame/src/github.com/glif-confidential/cli/cmd/root.go:46 +0x25
main.main()
	/Users/lanzafame/src/github.com/glif-confidential/cli/main.go:21 +0x17
```

### PR DESCRIPTION
**Pull request by lanzafame**
resolves #33

### CODE REVIEW

File: cmd/agent_pay_principal.go [hunk 1]
```diff
@@ -61,7 +62,10 @@ var payPrincipalCmd = &cobra.Command{
 
 		s.Stop()
 
-		fmt.Printf("Successfully paid %s FIL", args[0])
+		paidAmount := new(big.Int)
+		paidAmount.SetString(args[0], 10)
```
Comment (Schwartz10) [inline cmd/agent_pay_principal.go:66]: Let's use `parseFILAmount` helper here to consolidate logic

File: cmd/agent_pay_current.go [hunk 2]
```diff
@@ -53,7 +55,10 @@ var payToCurrentCmd = &cobra.Command{
 
 		s.Stop()
 
-		fmt.Printf("Successfully paid %s FIL", args[0])
+		paidAmount := new(big.Int)
+		paidAmount.SetString(args[0], 10)
```
Comment (Schwartz10) [inline cmd/agent_pay_current.go:59]: Same comment - let's use `parseFILAmount`

**Review by Schwartz10 — CHANGES_REQUESTED** [review]

**Review by Schwartz10 — APPROVED** [review]
